server {
    listen 80;

    # 정적 프론트엔드
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # /api/ 로 오는 요청은 api 컨테이너로 프록시 (이름으로 찾음)
    location /api/ {
        proxy_pass http://api:6000/;
    }
}
